# Generated by Django 3.2.9 on 2022-11-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('foto', models.ImageField(default='/UIMS/default_avatar_xugf2l.png', null=True, upload_to='UIMS')),
                ('division', models.IntegerField(blank=True, choices=[(0, 'Lainnya (Team Principal, Finance, Advisor, dll.)'), (1, 'Gokart'), (2, 'Electric Vehicle'), (3, 'Marketing')], null=True)),
                ('sub_division', models.IntegerField(blank=True, choices=[(0, 'Lainnya (Team Principal, Finance, Advisor, dll.)'), (1, 'Gokart 550'), (2, 'Gokart 551'), (3, 'E-Powertrain'), (4, 'Vehicle'), (5, 'Aerodynamics'), (6, 'Media'), (7, 'Relation'), (8, 'Sponsorship')], null=True)),
                ('jabatan', models.IntegerField(blank=True, choices=[(0, 'Team Principal'), (1, 'Finance'), (2, 'Advisor'), (3, 'Secretary'), (4, 'Driver'), (5, 'Chief Technical Officer'), (6, 'Manager'), (7, 'Staff'), (8, 'Mechanic')], null=True)),
            ],
        ),
    ]
