# Generated by Django 3.2.9 on 2022-12-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teammember_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='jabatan',
            field=models.CharField(blank=True, choices=[('TEAM PRINCIPAL', 'Team Principal'), ('FINANCE', 'Finance'), ('ADVISOR', 'Advisor'), ('SECRETARY', 'Secretary'), ('DRIVER', 'Driver'), ('CTO', 'Chief Technical Officer'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('MECHANIC', 'Mechanic')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='sub_division',
            field=models.CharField(blank=True, choices=[('OTHERS', 'Lainnya (Team Principal, Finance, Advisor, dll.)'), ('GOKART 550', 'Gokart 550'), ('GOKART 551', 'Gokart 551'), ('E-POWERTRAIN', 'E-Powertrain'), ('VEHICLE', 'Vehicle'), ('AERODYNAMICS', 'Aerodynamics'), ('MEDIA', 'Media'), ('RELATION', 'Relation'), ('SPONSORSHIP', 'Sponsorship')], max_length=200, null=True),
        ),
    ]
