# Generated by Django 4.0.6 on 2022-07-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='category',
        ),
    ]
