# Generated by Django 4.0.6 on 2022-07-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_divisionname_teamrole_division_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrole',
            name='division_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
