# Generated by Django 4.0.6 on 2022-07-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_teamrole_division_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrole',
            name='division_name',
        ),
        migrations.AddField(
            model_name='teamrole',
            name='division',
            field=models.IntegerField(blank=True, choices=[(0, 'Team Principal'), (1, 'Director'), (2, 'Powertrain'), (3, 'Vehicle'), (4, 'Internal'), (5, 'External')], null=True),
        ),
        migrations.AlterField(
            model_name='teamrole',
            name='division_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Team Principal'), (1, 'Technical Division'), (2, 'Non-Technical Division')], null=True),
        ),
    ]
