# Generated by Django 4.0.6 on 2022-07-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_remove_teamrole_division_name_teamrole_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrole',
            name='division_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Technical Division'), (2, 'Non-Technical Division')], null=True),
        ),
    ]
