# Generated by Django 4.0.6 on 2022-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_teamrole_division_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrole',
            name='division',
            field=models.IntegerField(choices=[(0, 'Team Principal'), (1, 'Director'), (2, 'Powertrain'), (3, 'Vehicle'), (4, 'Internal'), (5, 'External')]),
        ),
    ]
