# Generated by Django 4.0.6 on 2022-07-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_teamrole_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamrole',
            old_name='role',
            new_name='role_name',
        ),
    ]
