# Generated by Django 3.2.9 on 2022-11-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_rename_role_teamrole_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='angkatan',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.AddField(
            model_name='teammember',
            name='division',
            field=models.IntegerField(blank=True, choices=[(0, 'Lainnya (Team Principal, Finance, Advisor, dll.)'), (1, 'Gokart'), (2, 'Electric Vehicle'), (3, 'Marketing')], null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='jabatan',
            field=models.IntegerField(blank=True, choices=[(0, 'Team Principal'), (1, 'Finance'), (2, 'Advisor'), (3, 'Secretary'), (4, 'Driver'), (5, 'Chief Technical Officer'), (6, 'Manager'), (7, 'Staff'), (8, 'Mechanic')], null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='sub_division',
            field=models.IntegerField(blank=True, choices=[(0, 'Lainnya (Team Principal, Finance, Advisor, dll.)'), (1, 'Gokart 550'), (2, 'Gokart 551'), (3, 'E-Powertrain'), (4, 'Vehicle'), (5, 'Aerodynamics'), (6, 'Media'), (7, 'Relaton'), (8, 'Sponsorship')], null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='thumbnail',
            field=models.ImageField(upload_to='UIMS'),
        ),
        migrations.DeleteModel(
            name='TeamRole',
        ),
    ]
