# Generated by Django 3.2.9 on 2022-11-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20221105_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='sub_division',
            field=models.IntegerField(blank=True, choices=[(0, 'Lainnya (Team Principal, Finance, Advisor, dll.)'), (1, 'Gokart 550'), (2, 'Gokart 551'), (3, 'E-Powertrain'), (4, 'Vehicle'), (5, 'Aerodynamics'), (6, 'Media'), (7, 'Relation'), (8, 'Sponsorship')], null=True),
        ),
    ]
