# Generated by Django 3.2.9 on 2022-11-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_teammember_sub_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='foto',
            field=models.ImageField(default='C:\\Users\\Fathur\\Repos\\uims-backend\\uims\\media/default_picture.png', null=True, upload_to='UIMS'),
        ),
    ]
