# Generated by Django 3.2.9 on 2022-11-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_alter_teammember_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='foto',
            field=models.ImageField(default='default_picture.png', null=True, upload_to='UIMS'),
        ),
    ]
