# Generated by Django 3.2.9 on 2022-11-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_alter_teammember_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='foto',
            field=models.ImageField(default='/UIMS/default_avatar_xugf2l', null=True, upload_to='UIMS'),
        ),
    ]
