# Generated by Django 3.2.9 on 2022-11-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_alter_teammember_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
