# Generated by Django 4.0.6 on 2022-07-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_teamrole_division_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamrole',
            old_name='division_name',
            new_name='Division/Director Name',
        ),
    ]
